# Generated by Django 3.2 on 2022-05-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
    ]
