# Generated by Django 2.1.5 on 2021-02-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210202_1606'),
        ('user', '0003_auto_20210202_1606'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CV')),
            ],
            options={
                'verbose_name_plural': '应聘行为表',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=18, verbose_name='企业名称')),
                ('address', models.CharField(max_length=50, verbose_name='公司地址')),
                ('logo', models.ImageField(blank=True, default='static/img/default_img.jpg', null=True, upload_to='static/img/enterprise_logo/', verbose_name='企业logo')),
                ('nature', models.CharField(blank=True, choices=[('01', '国有企业'), ('02', '集体所有制企业'), ('03', '联营企业'), ('04', '三资企业'), ('05', '私营企业')], max_length=8, null=True, verbose_name='企业性质')),
            ],
            options={
                'verbose_name': '企业信息表',
            },
        ),
        migrations.CreateModel(
            name='NumberOfStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_number', models.IntegerField(blank=True, null=True, verbose_name='当前规模下限')),
                ('max_number', models.IntegerField(blank=True, null=True, verbose_name='当前规模上限')),
            ],
            options={
                'verbose_name': '员工规模表',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='岗位名称')),
                ('job_content', models.CharField(max_length=160, verbose_name='工作内容')),
                ('requirement', models.CharField(max_length=160, verbose_name='岗位基本要求')),
                ('is_posting', models.BooleanField(default=False, verbose_name='是否正在发布招聘')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseInfo', verbose_name='企业')),
            ],
            options={
                'verbose_name': '岗位信息表',
                'verbose_name_plural': '岗位信息表',
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_employers', models.IntegerField(blank=True, null=True, verbose_name='招聘人数')),
                ('city', models.CharField(max_length=18)),
                ('salary_min', models.IntegerField(verbose_name='最低入职工资')),
                ('salary_max', models.IntegerField(verbose_name='最高入职工资')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Education', verbose_name='学历要求')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.EnterpriseInfo', verbose_name='企业名字')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Position', verbose_name='岗位名称')),
            ],
            options={
                'verbose_name_plural': '招聘行为表',
            },
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': '领域表', 'verbose_name_plural': '领域表'},
        ),
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/field', verbose_name='分类图片'),
        ),
        migrations.AddField(
            model_name='enterpriseinfo',
            name='field',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_root': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.Field', verbose_name='领域'),
        ),
        migrations.AddField(
            model_name='enterpriseinfo',
            name='staff_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.NumberOfStaff'),
        ),
        migrations.AddField(
            model_name='applications',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Recruitment'),
        ),
    ]
