# Generated by Django 3.2 on 2022-05-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_auto_20220519_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseCooperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('enterprise_id', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='加入时间')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobHuntersCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('enterprise_id', models.IntegerField(blank=True, null=True)),
                ('collector', models.IntegerField(blank=True, null=True, verbose_name='企业协作id')),
            ],
            options={
                'verbose_name_plural': '求职者收藏表',
            },
        ),
        migrations.CreateModel(
            name='PositionsData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('view', models.IntegerField(default=0)),
                ('join', models.IntegerField(default=0)),
                ('collect', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '职位数据表',
            },
        ),
    ]
