# Generated by Django 2.1.5 on 2021-02-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20210224_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseinfo',
            name='nature',
            field=models.CharField(blank=True, choices=[(1, '国有企业'), (2, '集体所有制企业'), (3, '联营企业'), (4, '三资企业'), (5, '私营企业')], max_length=8, null=True, verbose_name='企业性质'),
        ),
    ]
