# Generated by Django 3.2 on 2022-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_enterprisecooperation_jobhunterscollection_positionsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecooperation',
            name='is_superuser',
            field=models.BooleanField(default=0),
        ),
    ]
