# Generated by Django 3.2 on 2022-05-31 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('enterprise', '0004_enterprisecooperation_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhunterscollection',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 17, 4, 19, 211940)),
        ),
    ]
