# Generated by Django 3.2 on 2022-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_jobhunterscollection_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhunterscollection',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
