# Generated by Django 3.2 on 2022-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_alter_jobhunterscollection_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('position_id', models.IntegerField(blank=True, null=True, verbose_name='职位id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '职位收藏表',
            },
        ),
    ]
