# Generated by Django 3.1 on 2021-04-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_recruitment_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pst_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_root': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.positionclass', verbose_name='岗位类别'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='岗位扩展名称（别称，默认为岗位类别）'),
        ),
    ]
