# Generated by Django 3.1 on 2021-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_auto_20210414_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='progress',
            field=models.IntegerField(blank=True, default=0, verbose_name='应聘进度'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='education',
            field=models.IntegerField(blank=True, choices=[(0, '无'), (1, '小学'), (2, '初中'), (3, '高中/中职/中专/技校'), (4, '高职/高专/技师学院'), (5, '本科/职业本科'), (6, '硕士研究生'), (7, '硕士博士生及以上')], null=True, verbose_name='最低学历要求'),
        ),
    ]
