# Generated by Django 2.1.5 on 2021-04-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_auto_20210421_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.AddField(
            model_name='position',
            name='fullname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='岗位扩展名称（别称，默认为岗位类别）'),
        ),
    ]
