# Generated by Django 2.1.5 on 2021-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0014_auto_20210426_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='applications',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='education',
            field=models.IntegerField(blank=True, choices=[(0, '无'), (1, '小学'), (2, '初中'), (3, '高中/中职/中专'), (4, '高职/高专'), (5, '本科/职业本科'), (6, '硕士研究生'), (7, '硕士博士生')], null=True, verbose_name='最低学历要求'),
        ),
    ]
