# Generated by Django 3.2.3 on 2021-05-19 02:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0004_settingchinesetag'),
        ('enterprise', '0015_auto_20210429_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedWhatever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_taggedwhatever_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_taggedwhatever_items', to='taggit.settingchinesetag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enterpriseinfo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='enterprise.TaggedWhatever', to='taggit.SettingChineseTag', verbose_name='Tags'),
        ),
    ]
