# Generated by Django 3.2.3 on 2021-05-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0007_remove_settingchinesetag_is_self_setting'),
        ('enterprise', '0016_auto_20210519_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfSettingTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.IntegerField(blank=True, choices=[(0, '企业'), (1, '用户'), (2, '简历'), (3, '职位')], default=0, verbose_name='所属实体')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggit.settingchinesetag', verbose_name='标签')),
            ],
        ),
    ]
