# Generated by Django 3.2.3 on 2021-05-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0018_auto_20210520_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelfSettingTags',
        ),
    ]
