# Generated by Django 3.2 on 2022-02-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificationInfo',
            fields=[
                ('cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_name', models.CharField(max_length=32)),
                ('cert_level',
                 models.IntegerField(blank=True, choices=[(0, '不分级'), (1, '初级'), (2, '中级'), (3, '高级')], null=True,
                                     verbose_name='证书等级')),
                ('issuing_unit', models.CharField(blank=True, max_length=32, null=True, verbose_name='发证单位')),
                ('cert_introduction', models.CharField(blank=True, max_length=256, null=True, verbose_name='证书简介')),
                ('testing_way', models.IntegerField(choices=[(0, '无考核'), (1, '笔试+实操'), (2, '笔试'), (3, '实操')], default=1,
                                                    verbose_name='考核方式')),
                ('aim_people', models.CharField(blank=True, max_length=64, null=True, verbose_name='针对人群')),
                ('cor_positions', models.CharField(blank=True, max_length=64, null=True, verbose_name='相关岗位')),
                ('expiry_date', models.CharField(blank=True, max_length=16, null=True, verbose_name='证书有效期')),
            ],
            options={
                'verbose_name_plural': '证书信息表',
            },
        ),
        migrations.CreateModel(
            name='classInfo',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_type',
                 models.IntegerField(blank=True, choices=[(0, '线上课'), (1, '线下课'), (2, '线上下结合')], null=True,
                                     verbose_name='班级类型')),
                ('class_period',
                 models.IntegerField(blank=True, choices=[(0, '周末班'), (1, '平时班')], null=True, verbose_name='周期类型')),
                ('class_status',
                 models.IntegerField(blank=True, choices=[(0, '未开始'), (1, '进行中'), (2, '已结束'), (3, '已关闭')], null=True,
                                     verbose_name='班级状态')),
                ('class_start_date', models.DateField(blank=True, null=True, verbose_name='预计开班时间')),
                ('class_end_date', models.DateField(blank=True, null=True, verbose_name='预计结课日期')),
                ('is_exam_exist', models.BooleanField(default=0, verbose_name='')),
                ('is_practice_exist', models.BooleanField(default=0, verbose_name='')),
                ('is_cert_exist', models.BooleanField(default=0, verbose_name='')),
                ('is_online_study_exist', models.BooleanField(default=0, verbose_name='')),
            ],
            options={
                'verbose_name_plural': '班级信息表',
            },
        ),
        migrations.CreateModel(
            name='courseInfo',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='课程名')),
                ('course_direction',
                 models.IntegerField(blank=True, choices=[(0, 'PLC'), (1, '工业机器人'), (2, '机器视觉')], null=True,
                                     verbose_name='课程方向')),
                ('course_type',
                 models.IntegerField(blank=True, choices=[(0, '技能提升班'), (1, '证书取证班'), (2, '就业班')], null=True,
                                     verbose_name='课程类别')),
                ('course_price', models.FloatField(blank=True, null=True, verbose_name='课程售价')),
                ('course_true_price', models.FloatField(blank=True, null=True, verbose_name='真实售价')),
            ],
            options={
                'verbose_name_plural': '课程信息表',
            },
        ),
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户/学员id')),
                ('student_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='全名')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('wechat_openid', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信号')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('sex', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别')),
                ('is_valid',
                 models.IntegerField(blank=True, choices=[(0, '未认证'), (1, '认证成功'), (2, '未通过认证'), (3, '认证审核中')],
                                     default=0, null=True, verbose_name='小鹅通账号认证')),
            ],
            options={
                'verbose_name_plural': '学员信息表',
            },
        ),
        migrations.CreateModel(
            name='teacherInfo',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='教师姓名')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号码')),
                ('wechat_openid', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信号')),
                ('level',
                 models.IntegerField(choices=[(0, '暂未获取'), (1, '助教'), (2, '初级讲师'), (3, '中级讲师'), (4, '高级讲师')], default=0,
                                     verbose_name='教师职级')),
                ('self_introduction',
                 models.CharField(blank=True, default='该教师简介暂未更新', max_length=120, null=True, verbose_name='教师简介')),
            ],
            options={
                'verbose_name_plural': '教师信息表',
            },
        ),
        migrations.CreateModel(
            name='classTeacherCon',
            fields=[
                ('class_teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_responsibility', models.CharField(blank=True, max_length=64, null=True, verbose_name='教师职责')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classinfo',
                                               verbose_name='班级')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.teacherinfo',
                                                 verbose_name='教师')),
            ],
            options={
                'verbose_name_plural': '班级-教师连接表',
            },
        ),
        migrations.CreateModel(
            name='classStudentCon',
            fields=[
                ('class_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_progress',
                 models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='线上学习进度')),
                ('exam_progress',
                 models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='线上考试进度')),
                ('cert_progress',
                 models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='证书进度')),
                ('practice_progress',
                 models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='实操进度')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classinfo',
                                               verbose_name='班级')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.studentinfo',
                                                 verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '班级-学生连接表',
            },
        ),
        migrations.CreateModel(
            name='classCourseCertCon',
            fields=[
                ('class_course_cert_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('cert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.certificationinfo',
                                              verbose_name='证书')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classinfo',
                                               verbose_name='班级')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.courseinfo',
                                                verbose_name='课程')),
            ],
            options={
                'verbose_name_plural': '班级-课程-证书连接表',
            },
        ),
    ]
