# Generated by Django 3.2 on 2022-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_alter_teacherinfo_teaching_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationinfo',
            name='cert_sample',
            field=models.ImageField(blank=True, default='static/img/default_img.jpg', null=True, upload_to='static/img/certification_samples', verbose_name='证书样图'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/default_img.jpg', null=True, upload_to='static/img/teachers', verbose_name='教师证件照'),
        ),
    ]
