# Generated by Django 3.2 on 2022-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0006_teacherinfo_teaching_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='ads_picture',
            field=models.ImageField(blank=True, default='static/img/default_img.jpg', null=True, upload_to='static/img/course_ads_pictures', verbose_name='课程宣传图'),
        ),
    ]
