# Generated by Django 3.2 on 2022-03-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0008_auto_20220307_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='failedUpdateRecords',
            fields=[
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cert.classinfo', verbose_name='班级id')),
                ('failed_date', models.DateField(blank=True, null=True, verbose_name='更新失败日期')),
                ('is_updated', models.BooleanField(blank=True, null=True, verbose_name='是否已补更新')),
            ],
            options={
                'verbose_name_plural': '线上课数据更新失败记录表',
            },
        ),
        migrations.CreateModel(
            name='updateDateRecords',
            fields=[
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cert.classinfo', verbose_name='班级id')),
                ('exam_update_date', models.DateField(blank=True, null=True, verbose_name='上次考试更新时间')),
                ('study_update_date', models.DateField(blank=True, null=True, verbose_name='上次线上课更新时间')),
            ],
            options={
                'verbose_name_plural': '数据更新时间记录表',
            },
        ),
        migrations.AlterModelOptions(
            name='classcoursecertcon',
            options={'verbose_name_plural': '班级-课程-证书关联表'},
        ),
        migrations.AlterModelOptions(
            name='classstudentcon',
            options={'verbose_name_plural': '班级-学生关联表'},
        ),
        migrations.AlterModelOptions(
            name='classteachercon',
            options={'verbose_name_plural': '班级-教师关联表'},
        ),
        migrations.AddField(
            model_name='classinfo',
            name='min_practice_score',
            field=models.FloatField(default=60, verbose_name='实训达标成绩'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='min_study_time',
            field=models.IntegerField(default=100, verbose_name='线上课达标时长（h）'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='is_cert_exist',
            field=models.BooleanField(default=0, verbose_name='是否关联证书'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='is_exam_exist',
            field=models.BooleanField(default=0, verbose_name='是否包含笔试'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='is_online_study_exist',
            field=models.BooleanField(default=0, verbose_name='是否包含线上课'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='is_practice_exist',
            field=models.BooleanField(default=0, verbose_name='是否包含实训'),
        ),
        migrations.CreateModel(
            name='classExamCon',
            fields=[
                ('class_exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='考试id')),
                ('min_score', models.FloatField(blank=True, default=60, null=True, verbose_name='考试达标成绩')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classinfo', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '班级-考试关联表',
            },
        ),
        # migrations.CreateModel(
        #     name='examRecords',
        #     fields=[
        #         ('class_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cert.classexamcon', verbose_name='')),
        #         ('join_time', models.DateTimeField(blank=True, null=True, verbose_name='参加考试时间')),
        #         ('exam_score', models.FloatField(blank=True, null=True, verbose_name='考试成绩')),
        #         ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.studentinfo', verbose_name='学生')),
        #     ],
        #     options={
        #         'verbose_name_plural': '考试结果记录表',
        #     },
        # ),
    ]
