# Generated by Django 3.2 on 2022-03-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_auto_20220314_1152'),
    ]

    operations = [

    ]
