# Generated by Django 3.2 on 2022-03-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0010_onlinestudyrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='practiceRecords',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='实训id')),
                ('available_times', models.IntegerField(default=3, verbose_name='剩余可实训次数')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='实训截止日期')),
                ('practice_score', models.FloatField(blank=True, null=True, verbose_name='最高实训成绩')),
                ('latest_update_date', models.DateField(auto_now=True, verbose_name='上次更新日期')),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classstudentcon', verbose_name='班级-学生')),
            ],
            options={
                'verbose_name_plural': '实训结果记录表',
            },
        ),
        migrations.CreateModel(
            name='onlineStudyRecords',
            fields=[
                ('online_study_id', models.AutoField(primary_key=True, serialize=False, verbose_name='实训id')),
                ('accumulated_time', models.FloatField(default=0, verbose_name='累计时长（h）')),
                ('latest_time', models.FloatField(default=0, verbose_name='上次新增时长（h）')),
                ('class_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classstudentcon', verbose_name='班级-学生')),
            ],
            options={
                'verbose_name_plural': '线上课时长记录表',
            },
        ),
    ]
