# Generated by Django 3.2 on 2022-03-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0011_onlinestudyrecords_practicerecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='examRecords',
            fields=[
                ('exam_record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='考试记录id')),
                ('join_time', models.DateTimeField(blank=True, null=True, verbose_name='参加考试时间')),
                ('exam_score', models.FloatField(blank=True, null=True, verbose_name='考试成绩')),
                ('class_exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classexamcon', verbose_name='')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.studentinfo', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '考试结果记录表',
            },
        ),
    ]
