# Generated by Django 3.2 on 2022-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0012_examrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_name',
            field=models.CharField(blank=True, default='未命名班级', max_length=64, null=True, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='classstudentcon',
            name='cert_progress',
            field=models.IntegerField(choices=[(0, '未达标'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='证书进度'),
        ),
        migrations.AlterField(
            model_name='classstudentcon',
            name='exam_progress',
            field=models.IntegerField(choices=[(0, '未达标'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='线上考试进度'),
        ),
        migrations.AlterField(
            model_name='classstudentcon',
            name='practice_progress',
            field=models.IntegerField(choices=[(0, '未达标'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='实操进度'),
        ),
        migrations.AlterField(
            model_name='classstudentcon',
            name='study_progress',
            field=models.IntegerField(choices=[(0, '未达标'), (1, '已完成'), (2, '已关闭')], default=2, verbose_name='线上学习进度'),
        ),
    ]
