# Generated by Django 3.2 on 2022-04-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0013_auto_20220330_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedupdaterecords',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.classinfo',
                                    verbose_name='班级id'),
        ),
        migrations.AddField(
            model_name='failedupdaterecords',
            name='failed_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='失败id'),
            preserve_default=False,
        ),

    ]
