# Generated by Django 2.0.1 on 2020-12-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]
    #
    # operations = [
    #     migrations.AddField(
    #         model_name='personalinfo',
    #         name='user_class',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserClass', verbose_name='用户类别'),
    #     ),
    # ]
