# Generated by Django 3.2 on 2021-12-20 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20210922_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxuserphonevalidation',
            name='is_expired',
        ),
        migrations.CreateModel(
            name='User_WxID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_id', models.CharField(max_length=100, null=True, verbose_name='用户微信号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户&绑定微信号映射表',
            },
        ),
    ]
