# Generated by Django 3.2 on 2022-07-21 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWordFieldClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='敏感词')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('state', models.IntegerField(choices=[(0, '使用中'), (1, '已禁用')], default=0)),
            ],
            options={
                'verbose_name_plural': '敏感词类别表',
            },
        ),
        migrations.CreateModel(
            name='SensitiveWordInfo',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('b09f91ad-bb6e-4a84-b398-38efa5252b52'), max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, verbose_name='敏感词')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('state', models.IntegerField(choices=[(0, '使用中'), (1, '已禁用')], default=0)),
                ('classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.sensitivewordfieldclassify', verbose_name='敏感词类别id')),
            ],
            options={
                'verbose_name_plural': '敏感词',
            },
        ),
    ]
