# Generated by Django 3.2 on 2022-07-21 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivewordinfo',
            name='uid',
            field=models.CharField(default=uuid.UUID('1e7e7f7c-4eb2-466e-afe3-009c65f50715'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
