# Generated by Django 3.2 on 2022-07-21 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_sensitivewordinfo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivewordfieldclassify',
            name='state',
            field=models.IntegerField(choices=[(1, '已禁用'), (0, '使用中')], default=0),
        ),
        migrations.AlterField(
            model_name='sensitivewordinfo',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='敏感词'),
        ),
        migrations.AlterField(
            model_name='sensitivewordinfo',
            name='state',
            field=models.IntegerField(choices=[(1, '已禁用'), (0, '使用中')], default=0),
        ),
        migrations.AlterField(
            model_name='sensitivewordinfo',
            name='uid',
            field=models.CharField(default=uuid.UUID('e5ae9dc5-eb88-4188-a715-5c326bed8267'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
