# Generated by Django 2.1.5 on 2021-02-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='major',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='所学专业名称'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='talent',
            field=models.CharField(max_length=8, null=True, verbose_name='特长/爱好'),
        ),
    ]
