# Generated by Django 3.1 on 2021-04-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0013_auto_20210421_1746'),
        ('cv', '0002_auto_20210202_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV_PositionClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': '简历-求职意向表',
            },
        ),
        migrations.RemoveField(
            model_name='cv',
            name='job_intention',
        ),
        migrations.AlterField(
            model_name='cv',
            name='computer_skill',
            field=models.IntegerField(blank=True, choices=[(0, '一般'), (1, '了解'), (2, '中等'), (3, '熟悉'), (4, '精通')], null=True, verbose_name='计算机技能水平'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='english_skill',
            field=models.IntegerField(blank=True, choices=[(0, '一般'), (1, '了解'), (2, '中等'), (3, '熟悉'), (4, '精通')], null=True, verbose_name='英语技能水平'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='cv_positionclass',
            name='cv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv', verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='cv_positionclass',
            name='position_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.positionclass', verbose_name='求职意向（岗位）类别'),
        ),
    ]
